### ISSUE TITLE
Login/registration page not sending data simultaneously back to the db

### ISSUE THREAD

**Issue by Saket6198** [SarthakVitmal/pce_comp_web_programming_lab_Sarthak_Vitmal#3]
please have a look at login.php file since both login and registration are on the same file, only the registration query is working but after the user registers  itself, the login part failes to validate/perform any of the desired function. I tried to name the buttons and then give those respective names to the php command namely the isset($_POST(' ')) but it still gives the same issue. Please have a look at it :)

**Comment by DrasticCoder** [comment]
I'll look into auth functionality and address the problem.

**Comment by Saket6198** [comment]
fixed the issue by separating both the files.
